## 4/1/2019

In [1]:
#Numpy
import numpy as np

In [2]:
#Creating numpy array using list
data1 = [1,2,3,4,5]
print(data1)
arr1 = np.array(data1) # list to array
print(arr1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
data2 = [range(1,5),range(5,9)]
print(data2)
arr2 = np.array(data2) #2d array
print(arr2) # display
my_list = arr2.tolist() # converting array to list
print(my_list) 

[range(1, 5), range(5, 9)]
[[1 2 3 4]
 [5 6 7 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [4]:
my_list = [11,22,33,44,55]
print(my_list)
arr3 = np.array(my_list)
print(arr3)

[11, 22, 33, 44, 55]
[11 22 33 44 55]


In [7]:
#examining the array
print(arr1)
print(arr2)
print(arr1.dtype) # finding datatypes
print(arr2.dtype)
print(arr1.ndim) # number of dimensions
print(arr2.ndim)
print(arr1.shape) # [2,4] axis-0 is rows, axis-1 cols  
print(arr2.shape) 
print(arr1.size) # total no. of elements
print(arr2.size)
print(len(arr1)) # size of first dimension
print(len(arr2))

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
int32
int32
1
2
(5,)
(2, 4)
5
8
5
2


In [11]:
# creating special type of arrays
print(np.zeros(10)) # array with 10 floating point(64) zero values
print(np.zeros((3,6))) # 2-d array filled with 0s
print(np.ones(10)) # array with 10 float64 one values

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
print(np.linspace(0,1,5)) # 0 to 1(inclusive) with 5 points 
print(np.logspace(0,3,4)) # 10^0 to 10^3 (inclusive) with 4 points

[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]


In [17]:
# arange is like range, except it returns an array
# (not a list)
int_array = np.arange(5)
print(int_array)
float_array = int_array.astype(float)
print(float_array)
print(float_array.dtype)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]
float64


In [26]:
matrix = np.arange(10,dtype=float)
print(matrix)
matrix = matrix.reshape(5,2)
print(matrix)
print(matrix.T) # Transpose of nd-array
matrix = matrix.reshape(10)
print(matrix)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[0. 2. 4. 6. 8.]
 [1. 3. 5. 7. 9.]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [36]:
# adding an axis
a = np.array([[0,1],[2,3]])
print(a)
a_col = a[:,np.newaxis]
print(a_col)

[[0 1]
 [2 3]]
[[[0 1]]

 [[2 3]]]


In [38]:
a = np.array([0,1,2,3])
a_col=a[:,np.newaxis]
print(a_col)
a_col=a[:,np.newaxis]
print(a_col)

[[0]
 [1]
 [2]
 [3]]
[[0]
 [1]
 [2]
 [3]]


In [37]:
# stack arrays
# stack flat arrays in columns
# selection: single item
data1 = [1,2,3,4,5]
print(data1)
arr1 = np.array(data1)
print(arr1)
print(arr1[0]) # 0th element, slices like a list
print(arr2)
print(arr2[0,3]) #  data at row no. 0 and col no. 3
print(arr2[0][3]) # alternative syntax

[1, 2, 3, 4, 5]
[1 2 3 4 5]
1
[[1 2 3 4]
 [5 6 7 8]]
4
4


In [42]:
# nd-array slicing
print(arr2)        # displaying
print(arr2[0,:])   #  full row 0 content
print(arr2[:,0])   # full column 0 content
print(arr2[:,:2])  # column strictly before index 2
print(arr2[:,2:])  # column strictyl after index 2 inclusive
print(arr2[:,1:4]) #  columns between 1 (inclusive) and 4(exclusive)
print(arr2[1,1:3])

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[1 5]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[2 3 4]
 [6 7 8]]
[6 7]


In [47]:
# views and copies
arr = np.arange(10)
print(arr)
print(arr[5:8])
arr[5:8] = 12 # array is mutable
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [50]:
arr = np.arange(10)
print(arr)
arr_view = arr[5:8] # Creating a view of the a array not creating a copy
print(arr_view)
arr_view[:] = 33 # updating array view not a array
print(arr_view)
print(arr) # but modifies back arr, arr_view

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[33 33 33]
[ 0  1  2  3  4 33 33 33  8  9]


In [51]:
arr = np.arange(10)
print(arr)
arr_copy = arr[5:8].copy() # Creating a copy of the a array not creating a view
print(arr_copy)
arr_copy[:] = 33 # updating array view not a array
print(arr_copy)
print(arr) # but not modifies back arr,only arr_copy

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[33 33 33]
[0 1 2 3 4 5 6 7 8 9]


In [52]:
# using boolean arrays
print(arr)
print(arr[arr>5]) # those values will get selected who will satisfy the condition given


[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [57]:
# boolean selection return a view with authorities
# the modification of the original array
print(arr)
arr[arr>5]=0
print(arr)
print(arr[arr%2==1])

[0 1 2 3 4 5 0 0 0 0]
[0 1 2 3 4 5 0 0 0 0]
[1 3 5]


In [64]:
names = np.array(['Bob','Joe','Will','Bob'])
print(names == 'Bob')

[ True False False  True]


In [65]:
print(names[names != 'Bob'])
print(names[(names=='Bob')|(names=='Will')])
# keywords and, or will not work here for ndarray
print(names)
names[names != 'Bob']='Patt'
print(names)

['Joe' 'Will']
['Bob' 'Will' 'Bob']
['Bob' 'Joe' 'Will' 'Bob']
['Bob' 'Patt' 'Patt' 'Bob']


In [74]:
names = np.array(['Bob','Joe','Will','Bob'])
print(names)
print(names[2])
print(names[names!=names[2]])
print(np.unique(names))

['Bob' 'Joe' 'Will' 'Bob']
Will
['Bob' 'Joe' 'Bob']
['Bob' 'Joe' 'Will']


In [81]:
#vectorized opeartions
nums=np.arange(5)
print(nums)
print(nums*10)
nums_res=nums**2
print(nums_res)
nums_res=np.sqrt(nums)
print(nums_res)

[0 1 2 3 4]
[ 0 10 20 30 40]
[ 0  1  4  9 16]
[0.         1.         1.41421356 1.73205081 2.        ]


In [82]:
nums_res=np.ceil(nums)
print(nums_res)
nums_res=np.floor(nums)
print(nums_res)
nums_res=np.isnan(nums)
print(nums_res)
values=np.array([10,20,30,40])
print(np.isnan(values))

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[False False False False False]
[False False False False]


In [86]:
print(nums)
print(nums+np.array([1,2,3,-4,5]))
print(np.maximum(nums,np.array([1,-2,3,-4,15])))
print(np.minimum(nums,np.array([1,-2,3,-4,15])))

[0 1 2 3 4]
[ 1  3  5 -1  9]
[ 1  1  3  3 15]
[ 0 -2  2 -4  4]


In [90]:
#calculating euclidean distance b/w 2 vectors
v1=np.random.randn(10)   #n=negative
v2=np.random.rand(10)
dist=np.sqrt(np.sum((v1-v2)**2))
print(v1)
print(v2)
print('dist=',dist)

[ 5.44090887e-01  1.84341269e+00  2.80310831e-01 -1.59982073e+00
 -2.36116377e+00  1.97496987e-01  5.10581741e-01  4.50415746e-01
 -9.89218853e-04 -7.20159840e-01]
[0.15240825 0.22661213 0.23008817 0.26745989 0.92997586 0.20324919
 0.22906302 0.69986728 0.71197934 0.05580388]
dist= 4.282554665080203


In [99]:
np.random.seed(0)
v1=np.random.randn(10)
v2=np.random.rand(10)
print(v1)
print(v2)

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
 0.0202184  0.83261985 0.77815675 0.87001215]


In [105]:
v3=np.random.rand(1)
v4=np.random.rand(3)*3        # 0 to 3
v5=np.random.rand(3)*3+5      # 5 to 8
v6=np.random.rand(3)*20-10    # -10 to 10
print(v3)
print(v4)
print(v5)
print(v6)

[0.11037514]
[1.96898877 0.41454885 0.58974709]
[6.10617551 7.46297969 5.29130383]
[ 6.75889815 -8.07803184  9.5291893 ]


In [107]:
print(np.random.randint(0,4,10))
print(np.random.randint(0,100,5))

[2 3 2 3 3 3 2 1 2 2]
[35 94 67 82 46]


In [112]:
#math and stats
rnd=np.random.randn(4,2) #random numbers in 4*2 array
print(rnd)
print(rnd.mean())
print(rnd.std())
print(rnd.argmin())    #index of minimum element
print(rnd.sum())
print(rnd.sum(axis=0))  #sum of each column
print(rnd.sum(axis=1))  #sum of each row

[[ 0.12691209  0.40198936]
 [ 1.8831507  -1.34775906]
 [-1.270485    0.96939671]
 [-1.17312341  1.94362119]]
0.1917128227836925
1.2725037650755138
3
1.53370258226954
[-0.43354561  1.9672482 ]
[ 0.52890146  0.53539164 -0.30108829  0.77049778]


In [115]:
#methods for boolean arrays
print(rnd)
print((rnd>0).sum())  # count of +ve no's
print((rnd>0).any())  # check if any 
print((rnd>0).all())  # check if all

[[ 0.12691209  0.40198936]
 [ 1.8831507  -1.34775906]
 [-1.270485    0.96939671]
 [-1.17312341  1.94362119]]
5
True
False


In [118]:
#reshape,transpose,flatten
n = np.arange(32).reshape(8,4)
print(n)
print(n.T)
print(n.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [123]:
#broadcasting
a =np.array([[0,0,0],
             [10,10,10],
             [20,20,20],
             [30,30,30]])
b=np.array([0,1,2])
print(a)
print(b)
print(a+b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [129]:
a =np.array([0,10,20,30])
a=a.reshape(4,1)
b=np.array([0,1,2,3])
print(a)
print(b)
print(a+b)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2 3]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [134]:
x=np.random.randn(4,2) #find for each column ,row index of min value 
print(x)
print(x.argmin(axis=0))
print(x.argmin(axis=1))

[[ 0.39600671 -1.09306151]
 [-1.49125759  0.4393917 ]
 [ 0.1666735   0.63503144]
 [ 2.38314477  0.94447949]]
[1 0]
[1 0 0 1]
